#!/bin/sh

tmpfile=$(mktemp /tmp/st-cmd-output.XXXXXX)
trap 'rm "$tmpfile"' 0 1 15

# copy stdin to a temporary file
sed -n "w $tmpfile"
sed -i 's/\x0//g' "$tmpfile"

# extract the command prompt string assuming that it's the first word in the last line
ps1="$(grep "\S" "$tmpfile" | tail -n 1 | sed 's/^\s*//' | cut -d' ' -f1)"

# pass to dmenu all lines that starts with the command prompt (except the last line)
chosen="$(grep -F "$ps1" "$tmpfile" | sed '$ d' | tac | dmenu -p "Copy which command's output?" -i -l 10 | sed 's/[^^]/[&]/g; s/\^/\\^/g')"

# remove all escape characters from the command prompt
eps1="$(echo "$ps1" | sed 's/[^^]/[&]/g; s/\^/\\^/g')"

# process the temp file - find the line with the selected command, then print all lines until the next command prompt, send the output to the clipboard
awk "/^$chosen$/{p=1;print;next} p&&/$eps1/{p=0};p" "$tmpfile" | xclip -selection clipboard
